###
POST http://127.0.0.1:8000/api/createAuthor/
content-type: application/json

{
    "name": "first Author"
}

###
POST http://127.0.0.1:8000/api/createBook/
content-type: application/json

{
    "name": "first Book",
    "authors": 1

}