###
POST http://127.0.0.1:8000/api/createAuthor/
content-type: application/json

{
    "name": "second author"
}

###
POST http://127.0.0.1:8000/api/createBook/
content-type: application/json

{
    "name": "second Book",
    "authors":2

}
###

# GET http://127.0.0.1:8000/api/author/<author_id>/
GET http://127.0.0.1:8000/api/author/1/
###

#GET http://127.0.0.1:8000/api/book/<book_id>/
GET http://127.0.0.1:8000/api/book/1/

###

GET http://127.0.0.1:8000/api/authors/

###

GET http://127.0.0.1:8000/api/books/
